.TH SODIUM 1 "Jun 8, 2015" "" "General Commands Manual"
.SH NAME
sodium - DVD cover art viewer & movie launcher

.SH SYNOPSIS
sodium <image path> <size> [video path]

.SH DESCRIPTION
Browse a directory of images which can be linked to movies to launch them.

.TP
.B image path
The path to the directory that contains the images to view
.TP
.B size
The size in pixels of the viewer window to create. Must be a multiple of 300
and at least 300.
.TP
.B video path
An optional path to the location where the videos are stored. This acts like a
base path and you can have any sort of tree under it.

.SH "ENVIRONMENT VARIABLES"
.TP 20
SODIUM_ANIMATION
This controls whether image animations are enabled. The default is enabled.
To disable, set this variable to 0.
.TP
SODIUM_DEBUG
Setting this to 1 enables debugging output.

.SH FILES
You can optionally create a file called \fBmovie-list\fR under
\fB~/.config/sodium/\fR. This is a mapping file that maps images to movies
and takes the form:-

.RS
image|movie|player|args[|runtime]
.RE

e.g

.RS
taken.jpg|action/Taken.mkv|vlc|--fullscreen|5375
.RE

The movie path can be relative to the video path if given at runtime. Or it
can be absolute. You can specify multiple space separated paths in there. See
the \fBREADME\fR for more details.

The runtime field is optional and can be used in sorting the movies in runtime
order.

.SH SOURCE
Source available at http://github.com/ac000/sodium under the GNU GPLv2

.SH AUTHORS
Andrew Clayton <andrew@digital-domain.net>
